server:
  port: 9080

spring:
  application:
    name: vg-ms-institution-management
  profiles:
    active: dev

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/sigei_institution
    username: postgres
    password: postgres

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/sigei_institution
    user: postgres
    password: postgres
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    pe.edu.vallegrande.sigei: DEBUG
    org.springframework.r2dbc: DEBUG

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html